service: bgc

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction"
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "logs:CreateLogGroup"
            - "logs:CreateLogStream"
            - "logs:PutLogEvents"
          Resource: "*"
  environment:
    CHROMIUM_PATH: "/opt/bin/chromium"
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
functions:
  getTopProducts:
    handler: handler.getTopProducts
    environment:
      CHROMIUM_PATH: "/opt/bin/chromium"
    events:
      - http:
          path: top-products
          method: get
          private: false
    layers:
      - arn:aws:lambda:us-east-1:764866452798:layer:chrome-aws-lambda:21
